--- 
title: "The Missing Many"
author: "Jes LaCourse"
date: "`r Sys.Date()`"
output_dir: "docs"
site: bookdown::bookdown_site
documentclass: book
description: "Decoding MIS Categories to Highlight the Systemic Masking of Native Students"
---

# The Missing Many {-}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 3)
```


:::: {.recap}
**With NASSSP programs rolling out across the state, our goal is to empower colleges to acknowledge and understand that their American Indian and Alaska Native student population extends beyond reporting standards.**


In Fall 2023, only about one in seven of Sierra College's American Indian and Alaska Native (AI/AN) met the AI/AN requirements for MIS reporting. Of the 709 students with AI/AN ancestry, 94 were reported to MIS as AI/AN.

American Indian and Alaska Native students who reported any Hispanic/Latinx or multiracial ancestry on their CCC application are not included in state and federal reporting as AI/AN students. That said, it’s critical that institutions include these students in on-site analytics and demographics, even if these students are not identified at a state or federal level.

::::

[_Learn More About the Native American Student Support and Success Program (NASSSP)](https://www.cccco.edu/-/media/CCCCO-Website/docs/memo/ess-23-12-system-wide-memo-nasssp-a11y.pdf)

This is a supplemental document to *The Missing Many: Decoding MIS Categories to Highlight the Systemic Masking of Native Students*, as presented to RP Conference, 2024. 

The following sections will provide a high-level overview of race and ethnicity data elements and methodologies. We will discuss data from the Chancellor's Office, including CCCApply and MIS data formats. A data sample of AI/AN, multiracial AI/AN, and Hispanic AI/AN students will be provided to allow participants to try out some of the techniques on their own. Set analysis, including Euler and UpSet plotting, will be applied and shared as well.
 



